name: 'semver-composite-action'
description: 'Semantic Versioning Composite Action a github composite action to figure out the next semantic version based on your last tags and merged PRs'
runs:
  using: "composite"
  steps:
    - name: SemVer
      shell: bash
      run: ./semver.sh