name: CI

on:
  push:
    branches: [ master, feature-*, hotfix-*, release-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ inputs.github-token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ github.run_number }}",
              sha: context.sha
            })