name: CI

on:
  push:
    branches: [ master, feature-*, hotfix-*, release-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}